spring:
  data:
    mongodb:
      port: 27017
      host: mongo
logging:
  level:
    org.springframework.security: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
server:
  port: 8080
file-service:
  host: file-service
  port: 8080