POST http://localhost:8080/api/v1/note
Content-Type: application/json

{
    "title": "title4324",
    "description": "description",
    "noteType": "Note",
    "tags": [{
        "id": "5cd1770f3adf4e1c9ec84777",
        "value": "best"
    }, {
        "id": "5cd19f033adf4e3c6654945f",
        "value": "dadfsgrsf"
    }]
}


###